package com.mart.main;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.extras.FlatAnimatedLafChange;
import com.mart.form.DoanhThuPanel;
import com.mart.form.Form1;
import com.mart.form.BangGia.BangGiaPanel;
import com.mart.form.ChiTieu.ChiTieuPanel;
import com.mart.form.ChungTu.ChungTuPanel;
import com.mart.form.ChuongTrinh.ChuongTrinhPanel;
import com.mart.form.DonHang.DonHangPanel;
import com.mart.form.HangDat.HangDatPanel;
import com.mart.form.HangHoa.HangHoaPanel;
import com.mart.form.HangHuy.HangHuyPanel;
import com.mart.form.HuongDan.HuongDanPanel;
import com.mart.form.KhachHang.KhachHangPanel;
import com.mart.form.LoaiHang.LoaiHangPanel;
import com.mart.form.NhaCC.NhaCCPanel;
import com.mart.form.NhanVien.NhanVienPanel;
import com.mart.form.ThietBi.ThietBiPanel;
import com.mart.menu.EventMenu;
import com.mart.menu.MainForm;
import com.mart.menu.MenuItem;
import com.mart.utils.Auth;
import com.mart.utils.Check;
import com.mart.utils.XImage;

import java.awt.Component;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JMenuItem;

/**
 *
 * @author raven
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        menu.addEventMenuSelected(new EventMenu() {
            @Override
            public void mainMenuSelected(MainForm mainForm, int index, MenuItem menuItem) {
            	mainForm.displayForm(new MainPanel());
            }

            @Override
            public void subMenuSelected(MainForm mainForm, int index, int subMenuIndex, Component menuItem) {
            	//Hang hóa
            	if(index==0 && subMenuIndex == 0) {
            		mainForm.displayForm(new HangHoaPanel());
            	} else if (index==0 && subMenuIndex == 1) {
					mainForm.displayForm(new HangDatPanel());
				} else if (index==0 && subMenuIndex == 2) {
					mainForm.displayForm(new HangHuyPanel());
				} else if (index==0 && subMenuIndex == 3) {
					mainForm.displayForm(new ChuongTrinhPanel());
				} else if (index==0 && subMenuIndex == 4) {
					if(Check.manage()) {
						mainForm.displayForm(new LoaiHangPanel());
					}
				} 
            	//Thu chi
            	if(index==1 && subMenuIndex==0) {
            		if(Check.manage()) {
            			mainForm.displayForm(new DoanhThuPanel());
            		}
            	} else if (index==1 && subMenuIndex == 1) {
            		if(Check.manage()) {
            			mainForm.displayForm(new ChiTieuPanel());
            		}
				}
            	//đơn hàng
            	if(index==2 && subMenuIndex == 0) {
            		if(Check.manage()) {
            			mainForm.displayForm(new DonHangPanel());
            		}
            	} else if (index==2 && subMenuIndex == 1) {
            		if(Check.manage()) {
            			mainForm.displayForm(new ChungTuPanel());
            		}
				}
            	//Thông tin
            	if(index==3 && subMenuIndex == 0) {
            		if(Check.manage()) {
            			mainForm.displayForm(new KhachHangPanel());
            		}
            	} else if (index==3 && subMenuIndex == 1) {
            		if(Check.manage()) {
            			mainForm.displayForm(new NhaCCPanel());
            		}
				} else if (index==3 && subMenuIndex == 2) {
					if(Check.manage()) {
						mainForm.displayForm(new NhanVienPanel());
					}
				}
            	//Hệ thống
            	if(index==4 && subMenuIndex == 0) {
            		if(Check.manage()) {
            			mainForm.displayForm(new ThietBiPanel());
            		}
            	} 
            }
        });
        menu.setSelectedIndex(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subMenu = new com.mart.menu.SubMenuPanel();
        menu = new com.mart.menu.Menu();
        lbLogo = new javax.swing.JLabel();
        mainMenuItem1 = new com.mart.menu.MenuItem();
        mainMenuItem3 = new com.mart.menu.MenuItem();
        mainMenuItem2 = new com.mart.menu.MenuItem();
        mainMenuItem4 = new com.mart.menu.MenuItem();
        mainMenuItem5 = new com.mart.menu.MenuItem();
        mainForm = new com.mart.menu.MainForm();
        menubar = new javax.swing.JMenuBar();
        menuThongTin = new javax.swing.JMenu();
        menuHeThong = new javax.swing.JMenu();
        menuMauNen = new javax.swing.JMenu();
        chDarkMode = new javax.swing.JCheckBoxMenuItem();
        mitemDoiMK = new JMenuItem();
        mitemDangXuat = new JMenuItem();
        mitemHuonngDan = new JMenuItem();
        mitemThongTinSanPham = new JMenuItem();
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(XImage.getAppIcon());
        setTitle("247Mart");

        subMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(80, 1, 1, 1));

        menu.setMainForm(mainForm);
        menu.setSubMenuPanel(subMenu);

        lbLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mart/icon/logo.png"))); // NOI18N
        lbLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbLogo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menu.add(lbLogo);

        mainMenuItem1.setBackground(new java.awt.Color(255, 45, 185));
        mainMenuItem1.setForeground(new java.awt.Color(75, 0, 243));
        mainMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mart/icon/menu1.png"))); // NOI18N
        mainMenuItem1.setText("Hàng hóa");
//        mainMenuItem1.setMenuIcon(new javax.swing.AbstractListModel() {
//            String[] strings = { "com/mart/icon/s1_1.png", "com/mart/icon/s1_2.png", "com/mart/icon/s1_3.png", "com/mart/icon/s1_4.png", "com/mart/icon/s1_5.png", "com/mart/icon/s1_6.png", "com/mart/icon/s1_7.png" };
//            public int getSize() { return strings.length; }
//            public Object getElementAt(int i) { return strings[i]; }
//        });
        mainMenuItem1.setMenuModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Hàng hóa", "Hàng đặt", "Hàng hủy", "Chương trình khuyến mãi","Loại hàng"};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menu.add(mainMenuItem1);

        mainMenuItem3.setBackground(new java.awt.Color(0, 217, 64));
        mainMenuItem3.setForeground(new java.awt.Color(74, 74, 74));
        mainMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mart/icon/menu2.png"))); // NOI18N
//        mainMenuItem3.setMenuIcon(new javax.swing.AbstractListModel() {
//            String[] strings = { "com/mart/icon/s2_1.png", "com/mart/icon/s2_2.png", "com/mart/icon/s2_3.png", "com/mart/icon/s2_4.png", "com/mart/icon/s2_5.png" };
//            public int getSize() { return strings.length; }
//            public Object getElementAt(int i) { return strings[i]; }
//        });
        mainMenuItem3.setMenuModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Doanh thu", "Chi tiêu"};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menu.add(mainMenuItem3);

        mainMenuItem2.setBackground(new java.awt.Color(255, 0, 0));
        mainMenuItem2.setForeground(new java.awt.Color(241, 255, 0));
        mainMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mart/icon/menu3.png"))); // NOI18N
//        mainMenuItem2.setMenuIcon(new javax.swing.AbstractListModel() {
//            String[] strings = { "com/mart/icon/s3_1.png", "com/mart/icon/s3_2.png", "com/mart/icon/s3_3.png" };
//            public int getSize() { return strings.length; }
//            public Object getElementAt(int i) { return strings[i]; }
//        });
        mainMenuItem2.setMenuModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Đơn hàng", "Chứng từ" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menu.add(mainMenuItem2);

        mainMenuItem4.setBackground(new java.awt.Color(8, 191, 196));
        mainMenuItem4.setForeground(new java.awt.Color(3, 66, 178));
        mainMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mart/icon/menu4.png"))); // NOI18N
//        mainMenuItem4.setMenuIcon(new javax.swing.AbstractListModel() {
//            String[] strings = { "com/mart/icon/s4_1.png", "com/mart/icon/s4_2.png", "com/mart/icon/s4_3.png" };
//            public int getSize() { return strings.length; }
//            public Object getElementAt(int i) { return strings[i]; }
//        });
        mainMenuItem4.setMenuModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Khách hàng", "Nhà cung cấp", "Nhân viên" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menu.add(mainMenuItem4);

        mainMenuItem5.setBackground(new java.awt.Color(0, 225, 100));
        mainMenuItem5.setForeground(new java.awt.Color(178, 17, 225));
        mainMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mart/icon/menu5.png"))); // NOI18N
//        mainMenuItem5.setText("mainMenuItem5");
        mainMenuItem5.setMenuModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Thiết bị" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menu.add(mainMenuItem5);
        
        mitemDangXuat.setText("Đăng xuất");
        mitemDangXuat.setIcon(new ImageIcon(getClass().getResource("/com/mart/icon/log-out.png")));
        mitemDangXuat.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				DangNhapFrame dangnhap = new DangNhapFrame();
				dangnhap.setVisible(true);
				Main.this.setVisible(false);;
			}
		});
        menuThongTin.add(mitemDangXuat);

        menuThongTin.setText("Thông tin");
        menubar.add(menuThongTin);
        
        menuMauNen.setText("Chế độ");

        chDarkMode.setText("Chế độ tối");
        chDarkMode.setIcon(new ImageIcon(getClass().getResource("/com/mart/icon/night-mode.png")));
        chDarkMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chDarkModeActionPerformed(evt);
            }
        });
        menuMauNen.add(chDarkMode);

        menubar.add(menuMauNen);

        setJMenuBar(menubar);
        
       
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(subMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainForm, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mainForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(menu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                    .addComponent(subMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chDarkModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chDarkModeActionPerformed
        if (chDarkMode.isSelected()) {
            EventQueue.invokeLater(() -> {
                FlatAnimatedLafChange.showSnapshot();
                FlatDarculaLaf.setup();
                FlatLaf.updateUI();
                FlatAnimatedLafChange.hideSnapshotWithAnimation();
            });
        } else {
            EventQueue.invokeLater(() -> {
                FlatAnimatedLafChange.showSnapshot();
                FlatIntelliJLaf.setup();
                FlatLaf.updateUI();
                FlatAnimatedLafChange.hideSnapshotWithAnimation();
            });
        }
    }//GEN-LAST:event_chDarkModeActionPerformed

    public static void main(String args[]) {
        FlatLaf.registerCustomDefaultsSource("com.mart.style");
        FlatIntelliJLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem chDarkMode;
    private javax.swing.JMenu menuThongTin;
    private javax.swing.JMenu menuHeThong;
    private javax.swing.JMenu menuMauNen;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JMenuItem mitemDoiMK;
    private javax.swing.JMenuItem mitemDangXuat;
    private javax.swing.JMenuItem mitemHuonngDan;
    private javax.swing.JMenuItem mitemThongTinSanPham;
    private com.mart.menu.MainForm mainForm;
    private com.mart.menu.MenuItem mainMenuItem1;
    private com.mart.menu.MenuItem mainMenuItem2;
    private com.mart.menu.MenuItem mainMenuItem3;
    private com.mart.menu.MenuItem mainMenuItem4;
    private com.mart.menu.MenuItem mainMenuItem5;
    private com.mart.menu.Menu menu;
    private com.mart.menu.SubMenuPanel subMenu;
    // End of variables declaration//GEN-END:variables
}
